name: Build and Publish to ACR

on:
  push:
    branches:
      - master
    tags: 
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set env variable for the version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Get key vault secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: 'rw-vault'
        secrets: 'containerRegistryPassword,containerRegistryUsername, containerRegistryLoginServer'
      id: getVaultSecrets

    - name: Login to Registry and Publish iIage
      uses: azure/docker-login@v1
      with:
        login-server: ${{ steps.getVaultSecrets.outputs.containerRegistryLoginServer }}
        username: ${{ steps.getVaultSecrets.outputs.containerRegistryUsername }}
        password: ${{ steps.getVaultSecrets.outputs.containerRegistryPassword }}
    - run: |
        docker build . -t ${{steps.getVaultSecrets.outputs.containerRegistryLoginServer}}/rw-nodejs:${{ env.RELEASE_VERSION }}
        docker push ${{steps.getVaultSecrets.outputs.containerRegistryLoginServer}}/rw-nodejs:${{ env.RELEASE_VERSION }}   
  



    

